/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@apizi/ui';


declare global {

  namespace StencilComponents {
    interface AliceLikesVampires {

    }
  }

  interface HTMLAliceLikesVampiresElement extends StencilComponents.AliceLikesVampires, HTMLStencilElement {}

  var HTMLAliceLikesVampiresElement: {
    prototype: HTMLAliceLikesVampiresElement;
    new (): HTMLAliceLikesVampiresElement;
  };
  interface HTMLElementTagNameMap {
    'alice-likes-vampires': HTMLAliceLikesVampiresElement;
  }
  interface ElementTagNameMap {
    'alice-likes-vampires': HTMLAliceLikesVampiresElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'alice-likes-vampires': JSXElements.AliceLikesVampiresAttributes;
    }
  }
  namespace JSXElements {
    export interface AliceLikesVampiresAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;