/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@bearer/ui';
import '@stencil/redux';


declare global {

  namespace StencilComponents {
    interface ListStarWarsCharacters {

    }
  }

  interface HTMLListStarWarsCharactersElement extends StencilComponents.ListStarWarsCharacters, HTMLStencilElement {}

  var HTMLListStarWarsCharactersElement: {
    prototype: HTMLListStarWarsCharactersElement;
    new (): HTMLListStarWarsCharactersElement;
  };
  interface HTMLElementTagNameMap {
    'list-star-wars-characters': HTMLListStarWarsCharactersElement;
  }
  interface ElementTagNameMap {
    'list-star-wars-characters': HTMLListStarWarsCharactersElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'list-star-wars-characters': JSXElements.ListStarWarsCharactersAttributes;
    }
  }
  namespace JSXElements {
    export interface ListStarWarsCharactersAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface SlackReminder {

    }
  }

  interface HTMLSlackReminderElement extends StencilComponents.SlackReminder, HTMLStencilElement {}

  var HTMLSlackReminderElement: {
    prototype: HTMLSlackReminderElement;
    new (): HTMLSlackReminderElement;
  };
  interface HTMLElementTagNameMap {
    'slack-reminder': HTMLSlackReminderElement;
  }
  interface ElementTagNameMap {
    'slack-reminder': HTMLSlackReminderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'slack-reminder': JSXElements.SlackReminderAttributes;
    }
  }
  namespace JSXElements {
    export interface SlackReminderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface SlackReminderDisplay {

    }
  }

  interface HTMLSlackReminderDisplayElement extends StencilComponents.SlackReminderDisplay, HTMLStencilElement {}

  var HTMLSlackReminderDisplayElement: {
    prototype: HTMLSlackReminderDisplayElement;
    new (): HTMLSlackReminderDisplayElement;
  };
  interface HTMLElementTagNameMap {
    'slack-reminder-display': HTMLSlackReminderDisplayElement;
  }
  interface ElementTagNameMap {
    'slack-reminder-display': HTMLSlackReminderDisplayElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'slack-reminder-display': JSXElements.SlackReminderDisplayAttributes;
    }
  }
  namespace JSXElements {
    export interface SlackReminderDisplayAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
