/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface AttachPullRequest {
    }
  }

  interface HTMLAttachPullRequestElement extends StencilComponents.AttachPullRequest, HTMLStencilElement {}

  var HTMLAttachPullRequestElement: {
    prototype: HTMLAttachPullRequestElement;
    new (): HTMLAttachPullRequestElement;
  };
  interface HTMLElementTagNameMap {
    'AttachPullRequest': HTMLAttachPullRequestElement;
  }
  interface ElementTagNameMap {
    'AttachPullRequest': HTMLAttachPullRequestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'AttachPullRequest': JSXElements.AttachPullRequestAttributes;
    }
  }
  namespace JSXElements {
    export interface AttachPullRequestAttributes extends HTMLAttributes {
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
