/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface SlackReminder {
    }
  }

  interface HTMLSlackReminderElement extends StencilComponents.SlackReminder, HTMLStencilElement {}

  var HTMLSlackReminderElement: {
    prototype: HTMLSlackReminderElement;
    new (): HTMLSlackReminderElement;
  };
  interface HTMLElementTagNameMap {
    'SlackReminder': HTMLSlackReminderElement;
  }
  interface ElementTagNameMap {
    'SlackReminder': HTMLSlackReminderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'SlackReminder': JSXElements.SlackReminderAttributes;
    }
  }
  namespace JSXElements {
    export interface SlackReminderAttributes extends HTMLAttributes {
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
