/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface listingGoats {
    }
  }

  interface HTMLlistingGoatsElement extends StencilComponents.listingGoats, HTMLStencilElement {}

  var HTMLlistingGoatsElement: {
    prototype: HTMLlistingGoatsElement;
    new (): HTMLlistingGoatsElement;
  };
  interface HTMLElementTagNameMap {
    'listingGoats': HTMLlistingGoatsElement;
  }
  interface ElementTagNameMap {
    'listingGoats': HTMLlistingGoatsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'listingGoats': JSXElements.listingGoatsAttributes;
    }
  }
  namespace JSXElements {
    export interface listingGoatsAttributes extends HTMLAttributes {
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
